[left]
  [left.cel_shading]
    boolean = "CEL_SHADING"
    name = "Cel Shading"
    default = true
  [left.cel_size]
    float = "CEL_SIZE"
    name = "Cel Thickness"
    min = 0.0
    default = 1.0
    max = 20.0
    require = "misc.cel_shading"
  [left.cel_intensity]
    float = "CEL_INTENSITY"
    name = "Cel Opactiy"
    min = 0.0
    default = 0.666666667
    max = 1.0
    require = "misc.cel_shading"

[right]
  [right.draw_depth]
    boolean = "DISPLAY_DEPTH"
    name = "Depth Buffer"
    default = false
  [right.draw_norms]
    boolean = "DISPLAY_NORMALS"
    name = "Display Normals"
    default = false

  [right.classic_fog]
    boolean = "PLANAR_FOG"
    name = "Classic Fog"
    default = false
