[left]
    [left.use_shadows]
        boolean = "USE_SHADOWS"
        name = "Enable Shadows"
        default = true
    [left.soft_shadows]
        boolean = "SOFT_PENUMUBRA"
        name = "Smooth Shadows"
        default = false
    [left.penumbra_steps]
        integer = "PENUMBRA_STEPS"
        name = "Shadow Smoothing"
        min = 0
        default = 8
        max = 256
        requires = "shadows.soft_shadows"

[right]
    [right.shadow_brightness]
        float = "SHADOW_BRIGHTNESSS"
        name = "Shadow Brightness"
        min = 0.0
        default = 0.4
        max = 1.0
    [right.penumbra_roundness]
        integer = "PENUMBRA_ROUNDNESS"
        name = "Shadow Roundness"
        min = 0
        default = 8
        max = 256
        requires = "shadows.soft_shadows"
